server.port: 9090

logging:
  level:
    ROOT: DEBUG
    com.ecomshop.deskplus: DEBUG

spring:
  datasource:
    url: jdbc:postgres://adyxaflcmrilmh:803e05406668a74d659674725cba8e3a510c50557cfbf34a964bbf81f895a562@ec2-18-215-96-54.compute-1.amazonaws.com:5432/d96c5ekhsp7cg5
    username: adyxaflcmrilmh
    password: 803e05406668a74d659674725cba8e3a510c50557cfbf34a964bbf81f895a562
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        hbm2ddl:
          auto: update
  mail:
    host: smtp.org
    port: 587
    username: 
    password: 
    properties:
      mail:
        transport.protocol: smtp
        smtp.starttls.enable: true
        smtp.starttls.required: true
        smtp.auth: true
        smtp.from: ss
        default-encoding: UTF-8
        test-connection: false

mail.from.name: 

stripe:
  api-key: 
  deskplus.default-plan: 

deskplus:
  base-url: http://localhost:9090/
  product-key: desk_plus
