server.port: 9090

logging:
  level:
    ROOT: INFO
    com.ecomshop.deskplus: INFO

spring:
  datasource:
    url: jdbc:postgres://ligvubrzhbzrkp:772bc85c927209977d4fb5d85298c21b48ff0aa0c629acd1ab3ec960070fce6d@ec2-54-196-111-158.compute-1.amazonaws.com:5432/d3u9lhr75o7f0v
    username: ligvubrzhbzrkp
    password: 772bc85c927209977d4fb5d85298c21b48ff0aa0c629acd1ab3ec960070fce6d
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        hbm2ddl:
          auto: update
  mail:
    host: smtp.org
    port: 587
    username: 
    password: 
    properties:
      mail:
        transport.protocol: smtp
        smtp.starttls.enable: true
        smtp.starttls.required: true
        smtp.auth: true
        smtp.from: ss
        default-encoding: UTF-8
        test-connection: false

mail.from.name: 

stripe:
  api-key: 
  deskplus.default-plan: 

deskplus:
  base-url: http://localhost:9090/
  product-key: desk_plus
